local_backend: true

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
backend:
  # name, repo and site_domain are configured through CMS.init
  base_url: https://sveltia-cms-auth.cloudflare-com-a47.workers.dev/
  commit_messages:
    create: "content: create {{collection}} “{{slug}}”"
    update: "content: update {{collection}} “{{slug}}”"
    delete: "content: delete {{collection}} “{{slug}}”"
    uploadMedia: "content: upload “{{path}}”"
    deleteMedia: "content: delete “{{path}}”"
    openAuthoring: "content: '{{message}}'"

collections:
  - label: "Stages"
    name: "stages"
    folder: "timetable/stages"
    create: true
    label_singular: "Stage"
    extension: "json"
    summary: "{{icon}} {{name}}"
    identifier_field: "name"
    slug: "{{name}}"
    fields:
      - name: "id"
        widget: "hidden"
        default: "{{uuid_shorter}}"
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "string"
      - label: "Days"
        name: "days"
        widget: "list"
        label_singular: "Day"
        collapsed: auto
        summary: "{{date | date('dddd')}} ({{date | date('YYYY-MM-DD')}})"
        fields:
          - label: "Date"
            name: "date"
            widget: "datetime"
            format: "YYYY-MM-DD"
            time_format: false
            default: "{{now}}"
          - label: "Acts"
            name: "acts"
            label_singular: "Act"
            widget: "list"
            collapsed: auto
            summary: "{{time}} - {{name}} - {{duration}}min"
            fields:
              - name: "id"
                widget: "hidden"
                default: "{{uuid_shorter}}"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - label: DJ 🎧
                    value: dj
                  - label: Band 🎸
                    value: band
                  - label: Performance 💃
                    value: performance
                  - label: Workshop 🧑‍🏫
                    value: workshop
                  - label: Other ❓
                    value: other
                default: dj
              - label: "Time"
                name: "time"
                widget: "datetime"
                format: "HH:mm"
                date_format: false
              - label: "Duration"
                name: "duration"
                widget: "number"
                value_type: "int"
                default: 120
  - label: "Pages"
    name: "pages"
    files:
      - name: festival
        label: Festival
        file: "timetable/festival.json"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Year"
            name: "year"
            widget: "string"
          - label: "Public URL"
            name: "publicUrl"
            widget: "string"
            hint: "The url is used for QR code generation."
          - label: "Stage order"
            required: false
            name: "stageOrder"
            multiple: true
            widget: "relation"
            collection: "stages"
            search_fields: ["name"]
            value_field: "id"
            display_fields: ["{{fields.icon}} {{fields.name}}"]
          - label: "Demo mode"
            name: "demoMode"
            widget: "boolean"
            hint: "If turned on, the act dates are overriden with the current date. Effectively pretends the festival is currently running. Turn off for production use!"
